"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import FeedbackTickets from "@/components/FeedbackTickets";

type ApiRequest = { id: string; endpoint: string; timestamp: string; status_code: number; response_time: number | null; request_method: string; error_code: string | null; error_message: string | null; request_input: unknown; response_output: unknown };
type User = { id: string; name: string | null; email: string | null; usage: { ai_uses: number } | null; credits: number; apiKeys: unknown[]; controls: { app_blocked: boolean; api_blocked: boolean; app_daily_ai_limit: number | null; api_rate_limit_per_min: number | null } | null };

export default function DevOperationsPage() {
  const [requests, setRequests] = useState<ApiRequest[]>([]); const [stats, setStats] = useState<Record<string, number | null>>({}); const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const [usage, people] = await Promise.all([fetch("/api/dev/api-usage"), fetch("/api/dev/users")]); if (!usage.ok || !people.ok) { setError("Unable to load operations data."); return; } const usageData = await usage.json(); setRequests(usageData.requests ?? []); setStats(usageData); setUsers(await people.json()); }, []);
  useEffect(() => { void load(); }, [load]);
  async function updateUser(user: User, change: Record<string, unknown>) { const res = await fetch("/api/dev/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: user.id, ...change }) }); if (!res.ok) { setError("User update failed."); return; } void load(); }
  return <main className="min-h-screen p-4 md:p-8" style={{ background: "var(--background)" }}><div className="max-w-6xl mx-auto space-y-7"><div className="flex justify-between items-center"><div><Link href="/dev" className="text-sm" style={{ color: "var(--accent)" }}>← Dev Center</Link><h1 className="text-2xl font-bold mt-2" style={{ color: "var(--foreground)" }}>Operations</h1></div><button onClick={() => void load()} className="rounded-lg px-3 py-2 text-sm" style={{ border: "1px solid var(--card-border)", color: "var(--foreground)" }}>Refresh</button></div>{error && <p style={{ color: "#ff453a" }}>{error}</p>}
    <section className="grid grid-cols-2 md:grid-cols-4 gap-3">{[["Requests (24h)", stats.totalRequests24h], ["Failures", stats.failedRequests24h], ["Error rate", stats.errorRate === null ? "—" : `${stats.errorRate}%`], ["Avg. response", stats.averageResponseMs === null ? "—" : `${stats.averageResponseMs} ms`]].map(([label, value]) => <div key={String(label)} className="rounded-xl p-4" style={{ background: "var(--card)", border: "1px solid var(--card-border)" }}><p className="text-xs" style={{ color: "var(--foreground)", opacity: .55 }}>{label}</p><p className="text-xl font-bold mt-1" style={{ color: "var(--foreground)" }}>{String(value ?? "—")}</p></div>)}</section>
    <section className="space-y-3"><h2 className="text-lg font-semibold" style={{ color: "var(--foreground)" }}>All API requests</h2><div className="overflow-auto rounded-xl" style={{ border: "1px solid var(--card-border)" }}><table className="w-full text-xs"><thead style={{ background: "var(--card)" }}><tr><th className="p-2 text-left">Time</th><th className="p-2 text-left">Request</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Error</th><th className="p-2 text-left">Diagnostics</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id} style={{ borderTop: "1px solid var(--card-border)", color: "var(--foreground)" }}><td className="p-2">{new Date(request.timestamp).toLocaleString()}</td><td className="p-2">{request.request_method} {request.endpoint}</td><td className="p-2">{request.status_code} {request.response_time === null ? "" : `(${request.response_time}ms)`}</td><td className="p-2">{request.error_code || request.error_message || "—"}</td><td className="p-2"><details><summary className="cursor-pointer">View</summary><pre className="mt-1 max-w-96 whitespace-pre-wrap">{JSON.stringify({ input: request.request_input, output: request.response_output }, null, 2)}</pre></details></td></tr>)}</tbody></table></div></section>
    <section className="space-y-3"><h2 className="text-lg font-semibold" style={{ color: "var(--foreground)" }}>User access and usage</h2>{users.map((user) => <div className="rounded-xl p-3 flex flex-wrap items-center gap-3" key={user.id} style={{ background: "var(--card)", border: "1px solid var(--card-border)", color: "var(--foreground)" }}><div className="min-w-48"><b className="text-sm">{user.name || user.email || user.id}</b><p className="text-xs opacity-60">AI today: {user.usage?.ai_uses ?? 0} · App credits: {user.credits} · API keys: {user.apiKeys.length}</p></div><button onClick={() => void updateUser(user, { appBlocked: !user.controls?.app_blocked })} className="rounded-lg px-2 py-1 text-xs" style={{ border: "1px solid var(--card-border)" }}>{user.controls?.app_blocked ? "Unblock app" : "Block app"}</button><button onClick={() => void updateUser(user, { apiBlocked: !user.controls?.api_blocked })} className="rounded-lg px-2 py-1 text-xs" style={{ border: "1px solid var(--card-border)" }}>{user.controls?.api_blocked ? "Unblock API" : "Block API"}</button><button onClick={() => void updateUser(user, { giftAppCredits: 5 })} className="rounded-lg px-2 py-1 text-xs" style={{ border: "1px solid var(--card-border)" }}>Gift 5 credits</button><label className="text-xs">App AI/day <input aria-label="App daily AI limit" type="number" min="0" defaultValue={user.controls?.app_daily_ai_limit ?? ""} onBlur={(event) => event.currentTarget.value !== "" && void updateUser(user, { appDailyAiLimit: Number(event.currentTarget.value) })} className="ml-1 w-14 rounded p-1" style={{ background: "var(--background)", border: "1px solid var(--card-border)" }} /></label><label className="text-xs">API/min <input aria-label="API per-minute limit" type="number" min="0" defaultValue={user.controls?.api_rate_limit_per_min ?? ""} onBlur={(event) => event.currentTarget.value !== "" && void updateUser(user, { apiRateLimitPerMin: Number(event.currentTarget.value) })} className="ml-1 w-14 rounded p-1" style={{ background: "var(--background)", border: "1px solid var(--card-border)" }} /></label></div>)}</section>
    <FeedbackTickets devMode />
  </div></main>;
}
