"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
function itemSlug(name: string): string { return "closet-item-" + name.toLowerCase().replace(/[^a-z0-9]+/g, "-"); }
export default function ClosetManager({ initialItems, highlight }: { initialItems: string[]; highlight?: string | null }) {
  const [items, setItems] = useState(initialItems); const [newItem, setNewItem] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [editing, setEditing] = useState<string | null>(null); const [editValue, setEditValue] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const selectedSet = useMemo(() => new Set(selected), [selected]);
  useEffect(() => { if (!highlight) return; const target = document.getElementById(itemSlug(highlight)); if (!target) return; target.scrollIntoView({ behavior: "smooth", block: "center" }); target.style.boxShadow = "0 0 0 3px var(--accent)"; const timeout = setTimeout(() => { target.style.boxShadow = ""; }, 3000); return () => clearTimeout(timeout); }, [highlight, items]);
  async function save(next: string[]) { setBusy(true); setError(null); const res = await fetch("/api/closet", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: next }) }); setBusy(false); if (!res.ok) { setError((await res.json().catch(() => ({}))).error ?? "Could not save closet."); return false; } const data = await res.json(); setItems(data.items ?? next); return true; }
  async function add(event: FormEvent) { event.preventDefault(); const item = newItem.trim(); if (!item) return; if (await save([...items, item])) setNewItem(""); }
  async function commitEdit(item: string) { const value = editValue.trim(); if (!value) return; if (await save(items.map((current) => current === item ? value : current))) setEditing(null); }
  async function deleteSelected() { if (!selected.length || !window.confirm(`Remove ${selected.length} selected item${selected.length === 1 ? "" : "s"}?`)) return; if (await save(items.filter((item) => !selectedSet.has(item)))) setSelected([]); }
  return <div className="rounded-2xl p-6 space-y-4" style={{ background: "var(--card)", border: "1px solid var(--card-border)", boxShadow: "0 2px 12px rgba(0,0,0,0.06)" }}><div className="flex items-center justify-between"><div><h1 className="text-xl font-semibold" style={{ color: "var(--foreground)" }}>👕 My Closet</h1><p className="text-xs mt-1" style={{ color: "var(--foreground)", opacity: .5 }}>{items.length} item{items.length === 1 ? "" : "s"} in your wardrobe</p></div><button onClick={() => setSelected(selected.length === items.length ? [] : items)} className="text-xs underline" style={{ color: "var(--accent)" }}>{selected.length === items.length ? "Clear selection" : "Select all"}</button></div><form onSubmit={add} className="flex gap-2"><input value={newItem} onChange={(event) => setNewItem(event.target.value)} maxLength={200} placeholder="Add an item, e.g. Blue denim jacket" className="min-w-0 flex-1 rounded-xl px-3 py-2 text-sm" style={{ background: "var(--background)", color: "var(--foreground)", border: "1px solid var(--card-border)" }} /><button disabled={busy || !newItem.trim()} className="rounded-xl px-3 py-2 text-sm font-semibold" style={{ background: "var(--accent)", color: "#fff" }}>Add</button></form>{error && <p role="alert" className="text-xs" style={{ color: "#ff3b30" }}>{error}</p>}{selected.length > 0 && <button onClick={() => void deleteSelected()} disabled={busy} className="rounded-xl px-3 py-2 text-xs" style={{ color: "#ff3b30", border: "1px solid rgba(255,59,48,.35)" }}>Delete selected ({selected.length})</button>}{!items.length ? <div className="rounded-xl p-5 text-center" style={{ background: "var(--background)", color: "var(--foreground)", opacity: .6 }}>Your closet is empty. Add an item above to get started.</div> : <ul className="space-y-1.5">{items.map((item) => <li key={item} id={itemSlug(item)} className="rounded-xl px-3 py-2.5 text-sm flex items-center gap-2" style={{ background: "var(--background)", border: "1px solid var(--card-border)", color: "var(--foreground)" }}><input aria-label={`Select ${item}`} type="checkbox" checked={selectedSet.has(item)} onChange={() => setSelected((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current, item])} />{editing === item ? <><input autoFocus value={editValue} onChange={(event) => setEditValue(event.target.value)} className="min-w-0 flex-1 rounded px-2 py-1" style={{ background: "var(--card)", border: "1px solid var(--card-border)" }} /><button onClick={() => void commitEdit(item)} className="text-xs underline">Save</button><button onClick={() => setEditing(null)} className="text-xs underline">Cancel</button></> : <><span className="flex-1">👗 {item}</span><button onClick={() => { setEditing(item); setEditValue(item); }} className="text-xs underline">Edit</button></>}</li>)}</ul>}</div>;
}
