"use client";

import { useCallback, useEffect, useState } from "react";

type Key = { id: string; key_preview: string; nickname?: string | null; folder?: string | null; revoked: boolean };
type Wallet = { isPro: boolean; isDev: boolean; moneyCreditCents: number; appCredits: number; apiCredits: number };

export default function CreditCenter({ keys, onChanged }: { keys: Key[]; onChanged: () => Promise<void> }) {
  const [wallet, setWallet] = useState<Wallet | null>(null); const [selectedKeyId, setSelectedKeyId] = useState(""); const [message, setMessage] = useState<string | null>(null); const [donateOpen, setDonateOpen] = useState(false);
  const load = useCallback(async () => { const res = await fetch("/api/credits"); if (!res.ok) return; setWallet(await res.json()); }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!selectedKeyId && keys.find((key) => !key.revoked)) setSelectedKeyId(keys.find((key) => !key.revoked)?.id ?? ""); }, [keys, selectedKeyId]);
  async function allocate() { if (!selectedKeyId) return; const res = await fetch("/api/credits", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ keyId: selectedKeyId, moneyCreditCents: 100 }) }); const data = await res.json().catch(() => ({})); setMessage(res.ok ? `Allocated ${data.allocatedApiCredits} API Credit.` : data.error ?? "Allocation failed."); if (res.ok) { await Promise.all([load(), onChanged()]); } }
  const active = keys.filter((key) => !key.revoked);
  return <section className="rounded-2xl p-6 space-y-4" style={{ background: "var(--card)", border: "1px solid var(--card-border)" }}><div className="flex justify-between gap-4 flex-wrap"><div><p className="text-xs font-semibold uppercase tracking-widest" style={{ color: "var(--foreground)", opacity: .45 }}>Credits</p><p className="text-xs mt-1" style={{ color: "var(--foreground)", opacity: .58 }}>Keep money, API, and App Credit separate. $1.00 AUD converts to 50 API Credit for a key you choose.</p></div><button onClick={() => setDonateOpen(true)} className="rounded-xl px-3 py-2 text-xs font-semibold btn-interact" style={{ background: "var(--accent)", color: "#fff" }}>Get credits</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[["$ Credit (AUD)", wallet ? (wallet.isDev ? "Unlimited" : `$${(wallet.moneyCreditCents / 100).toFixed(2)}`) : "—"], ["API Credit", wallet?.isDev ? "Unlimited" : wallet?.apiCredits ?? "—"], ["App Credit", wallet?.isDev ? "Unlimited" : wallet?.appCredits ?? "—"]].map(([label, amount]) => <div key={String(label)} className="rounded-xl p-3" style={{ background: "var(--background)" }}><p className="text-xs opacity-55">{label}</p><p className="text-xl font-semibold mt-1">{amount}</p></div>)}</div>
    {wallet?.isPro && <p className="text-xs" style={{ color: "var(--foreground)", opacity: .55 }}>Your Pro plan receives $1.00 AUD credit each calendar month.</p>}
    {(wallet?.moneyCreditCents ?? 0) >= 100 && active.length > 0 && <div className="flex flex-wrap gap-2 items-center"><select value={selectedKeyId} onChange={(event) => setSelectedKeyId(event.target.value)} className="rounded-xl px-3 py-2 text-xs" style={{ background: "var(--background)", color: "var(--foreground)", border: "1px solid var(--card-border)" }}>{active.map((key) => <option key={key.id} value={key.id}>{key.folder ? `${key.folder} / ` : ""}{key.nickname || key.key_preview}</option>)}</select><button onClick={() => void allocate()} className="rounded-xl px-3 py-2 text-xs font-semibold" style={{ border: "1px solid var(--card-border)" }}>Allocate $1 → 50 API Credit</button></div>}
    {message && <p role="status" className="text-xs" style={{ color: message.includes("failed") || message.includes("Insufficient") ? "#ff3b30" : "#34c759" }}>{message}</p>}
    {donateOpen && <div className="fixed inset-0 z-[80] flex items-center justify-center p-4"><button className="absolute inset-0 bg-black/50" aria-label="Close donation dialog" onClick={() => setDonateOpen(false)} /><div className="relative max-w-sm rounded-2xl p-6 space-y-3" style={{ background: "var(--card)", color: "var(--foreground)", border: "1px solid var(--card-border)" }}><p className="text-3xl">☕</p><h2 className="text-lg font-bold">Support Sky Style</h2><p className="text-sm opacity-70">Credit purchases are not live yet. If Sky Style helps you, a donation helps cover weather and AI costs while this feature is prepared.</p><a href="https://buymeacoffee.com/coolmanyt" target="_blank" rel="noreferrer" className="inline-block rounded-xl px-4 py-2 text-sm font-semibold" style={{ background: "var(--accent)", color: "#fff" }}>Donate</a><button onClick={() => setDonateOpen(false)} className="block text-xs underline">Not now</button></div></div>}
  </section>;
}
